.TH REQUIREMENT 1 "26 October 2019"
.SH NAME
basic-information \- Assignment 2, Part B, Requirement 1
.SH SYNOPSIS
.B basic-information [-d -f -h -i -u -v]
.SH DESCRIPTION
.B basic-information
takes in arguments and displays the following infomation based on these 
arguments: amount of free and occupied memory in human readable format, 
amount of disk space free and in human readable format, network 
connection information and the system uptime.
.SH OPTIONS
.IP -d
Show disk free information.
.IP -f
Show memory free information.
.IP -h
Display this help and exit.
.IP -h
Display this help and exit.
.IP -i
Show network interface information.
.IP -u
Show uptime.
.IP -v
Display version number.
.SH FILES
.SH ENVIRONMENT
.SH DIAGNOSTICS
.BUGS
Bugs? what bugs.
.AUTHOR
Lance Bailey   s3242313@student.rmit.edu.au
.SH SEE ALSO
.BR df(1),
.BR free (1),
.BR ifconfig (8),
.BR uptime (1)
